NsReleaseLock prop was dropped
NethServer/nethserver-subscription pull request #21
Opened 2019-01-31 11:55 UTC by DavidePrincipi

NethServer/dev#5704

2019-02-04 14:58 UTC, gsanchietti approved these changes

2019-02-04 15:55 UTC, gsanchietti requested changes
Delete also /etc/yum/vars/nsrelease/20subscription template.

2019-02-05 08:11 UTC, DavidePrincipi commented
@gsanchietti if we remove that template, the automatic upgrade of subscriptions must be implemented by an action

2019-02-18 08:48 UTC, gsanchietti approved these changes

2019-02-18 09:40 UTC, merged