Enable ExtraRepositories in subscription
NethServer/nethserver-subscription pull request #41
Opened 2021-02-12 09:32 UTC by stephdl

Enable extra repositories for subscription

2021-02-12 10:22 UTC, gsanchietti approved these changes
It seems good to me, but let's wait Davide approval

2021-02-12 13:27 UTC, DavidePrincipi requested changes
Thank you for this PR!

Please remove the trailing end-of-line characters! The modified template fragments must produce an empty string as output.

Question: is there any reason to consider the `ExtraRepositories` prop only with an enabled subscription? I think it can be useful also for community users as well...

2021-02-12 13:27 UTC, DavidePrincipi commented on root/etc/e-smith/templates/etc/nethserver/eorepo.conf/20subscription
> +}
Remove EOL at EOF

2021-02-12 13:27 UTC, DavidePrincipi commented on root/etc/e-smith/templates/etc/nethserver/pkginfo.conf/20subscription
> +}
Remove EOL at EOF

2021-02-12 13:32 UTC, stephdl commented
> Question: is there any reason to consider the ExtraRepositories prop only with an enabled subscription? I think it can be useful also for community users as well...

It is the same problem I faced as an owner of repository, make this repo enabled after the event software-repos-save, I do not know, I would prefer that the sys-admin or the developer push a fragment to eorepo, however simplicity is often good too

I would like the advice of @gsanchietti

2021-02-12 13:37 UTC, DavidePrincipi commented
> I would prefer that the sys-admin or the developer push a fragment to eorepo, however simplicity is often good too

Yes I agree here. The NethServer developer should provide a fragment for eorepo in his `customrepo-release.rpm`. 

However a NethServer user might want to enable a third-party repo, for say a custom kernel module or whatever non-NethServer related addon... In this scenario the new prop would be useful.

2021-02-12 13:43 UTC, gsanchietti commented
> It is the same problem I faced as an owner of repository, make this repo enabled after the event software-repos-save, I do not know, I would prefer that the sys-admin or the developer push a fragment to eorepo, however simplicity is often good too

We can enable use the prop if if the subscription is not enabled, it's ok for me ;)

2021-02-15 08:01 UTC, DavidePrincipi reviewed
I saw the code update however the `ExtraRepositories` seems still subject to an enabled subscription. From the last comment by Giacomo, I was expecting to see it honored unconditionally...

2021-02-15 08:01 UTC, DavidePrincipi commented on README.rst
> +Enable extra repositories in subscription
```suggestion
Enable extra repositories
```

2021-02-15 08:03 UTC, DavidePrincipi commented on README.rst
> +- ``ExtraRepositories``: Enable extra repositories in the subscription (comma separated : nethforge,repoA,repoB).
```suggestion
- ``ExtraRepositories``: Enable extra repositories (comma separated : nethforge,repoA,repoB).
```

2021-02-15 08:57 UTC, gsanchietti requested changes
Please add an empty `ExtraRepositories` prop to db defaults

2021-02-15 09:04 UTC, gsanchietti approved these changes

2021-02-15 09:10 UTC, merged